export const CLICK_UPDATE_VALUE = 'CLICK_UPDATE_VALUE';
export const CLICK_CHANGE_THEME_VALUE = 'CLICK_CHANGE_THEME_VALUE';
export const CLICK_CHANGE_LANG_VALUE = 'CLICK_CHANGE_LANG_VALUE';
export const EVENT_CHECKAUTH_VALUE = 'EVENT_CHECKAUTH_VALUE';